export const errors: {[key: number]: {code: string; desc: string}} = {
    1: {code: 'EPERM', desc: 'Operation not permitted'},
    2: {code: 'ENOENT', desc: 'No such file or directory'},
    3: {code: 'ESRCH', desc: 'No such process'},
    4: {code: 'EINTR', desc: 'Interrupted system call'},
    5: {code: 'EIO', desc: 'I/O error'},
    6: {code: 'ENXIO', desc: 'No such device or address'},
    7: {code: 'E2BIG', desc: 'Arg list too long'},
    8: {code: 'ENOEXEC', desc: 'Exec format error'},
    9: {code: 'EBADF', desc: 'Bad file number'},
    10: {code: 'ECHILD', desc: 'No child processes'},
    11: {code: 'EAGAIN', desc: 'Try again'},
    12: {code: 'ENOMEM', desc: 'Out of memory'},
    13: {code: 'EACCES', desc: 'Permission denied'},
    14: {code: 'EFAULT', desc: 'Bad address'},
    15: {code: 'ENOTBLK', desc: 'Block device required'},
    16: {code: 'EBUSY', desc: 'Device or resource busy'},
    17: {code: 'EEXIST', desc: 'File exists'},
    18: {code: 'EXDEV', desc: 'Cross-device link'},
    19: {code: 'ENODEV', desc: 'No such device'},
    20: {code: 'ENOTDIR', desc: 'Not a directory'},
    21: {code: 'EISDIR', desc: 'Is a directory'},
    22: {code: 'EINVAL', desc: 'Invalid argument'},
    23: {code: 'ENFILE', desc: 'File table overflow'},
    24: {code: 'EMFILE', desc: 'Too many open files'},
    25: {code: 'ENOTTY', desc: 'Not a typewriter'},
    26: {code: 'ETXTBSY', desc: 'Text file busy'},
    27: {code: 'EFBIG', desc: 'File too large'},
    28: {code: 'ENOSPC', desc: 'No space left on device'},
    29: {code: 'ESPIPE', desc: 'Illegal seek'},
    30: {code: 'EROFS', desc: 'Read-only file system'},
    31: {code: 'EMLINK', desc: 'Too many links'},
    32: {code: 'EPIPE', desc: 'Broken pipe'},
    33: {code: 'EDOM', desc: 'Math argument out of domain of func'},
    34: {code: 'ERANGE', desc: 'Math result not representable'},
    35: {code: 'EDEADLK', desc: 'Resource deadlock would occur'},
    36: {code: 'ENAMETOOLONG', desc: 'File name too long'},
    37: {code: 'ENOLCK', desc: 'No record locks available'},
    38: {code: 'ENOSYS', desc: 'Function not implemented'},
    39: {code: 'ENOTEMPTY', desc: 'Directory not empty'},
    40: {code: 'ELOOP', desc: 'Too many symbolic links encountered'},
    42: {code: 'ENOMSG', desc: 'No message of desired type'},
    43: {code: 'EIDRM', desc: 'Identifier removed'},
    44: {code: 'ECHRNG', desc: 'Channel number out of range'},
    45: {code: 'EL2NSYNC', desc: 'Level 2 not synchronized'},
    46: {code: 'EL3HLT', desc: 'Level 3 halted'},
    47: {code: 'EL3RST', desc: 'Level 3 reset'},
    48: {code: 'ELNRNG', desc: 'Link number out of range'},
    49: {code: 'EUNATCH', desc: 'Protocol driver not attached'},
    50: {code: 'ENOCSI', desc: 'No CSI structure available'},
    51: {code: 'EL2HLT', desc: 'Level 2 halted'},
    52: {code: 'EBADE', desc: 'Invalid exchange'},
    53: {code: 'EBADR', desc: 'Invalid request descriptor'},
    54: {code: 'EXFULL', desc: 'Exchange full'},
    55: {code: 'ENOANO', desc: 'No anode'},
    56: {code: 'EBADRQC', desc: 'Invalid request code'},
    57: {code: 'EBADSLT', desc: 'Invalid slot'},
    59: {code: 'EBFONT', desc: 'Bad font file format'},
    60: {code: 'ENOSTR', desc: 'Device not a stream'},
    61: {code: 'ENODATA', desc: 'No data available'},
    62: {code: 'ETIME', desc: 'Timer expired'},
    63: {code: 'ENOSR', desc: 'Out of streams resources'},
    64: {code: 'ENONET', desc: 'Machine is not on the network'},
    65: {code: 'ENOPKG', desc: 'Package not installed'},
    66: {code: 'EREMOTE', desc: 'Object is remote'},
    67: {code: 'ENOLINK', desc: 'Link has been severed'},
    68: {code: 'EADV', desc: 'Advertise error'},
    69: {code: 'ESRMNT', desc: 'Srmount error'},
    70: {code: 'ECOMM', desc: 'Communication error on send'},
    71: {code: 'EPROTO', desc: 'Protocol error'},
    72: {code: 'EMULTIHOP', desc: 'Multihop attempted'},
    73: {code: 'EDOTDOT', desc: 'RFS specific error'},
    74: {code: 'EBADMSG', desc: 'Not a data message'},
    75: {code: 'EOVERFLOW', desc: 'Value too large for defined data type'},
    76: {code: 'ENOTUNIQ', desc: 'Name not unique on network'},
    77: {code: 'EBADFD', desc: 'File descriptor in bad state'},
    78: {code: 'EREMCHG', desc: 'Remote address changed'},
    79: {code: 'ELIBACC', desc: 'Can not access a needed shared library'},
    80: {code: 'ELIBBAD', desc: 'Accessing a corrupted shared library'},
    81: {code: 'ELIBSCN', desc: '.lib section in a.out corrupted'},
    82: {code: 'ELIBMAX', desc: 'Attempting to link in too many shared libraries'},
    83: {code: 'ELIBEXEC', desc: 'Cannot exec a shared library directly'},
    84: {code: 'EILSEQ', desc: 'Illegal byte sequence'},
    85: {code: 'ERESTART', desc: 'Interrupted system call should be restarted'},
    86: {code: 'ESTRPIPE', desc: 'Streams pipe error'},
    87: {code: 'EUSERS', desc: 'Too many users'},
    88: {code: 'ENOTSOCK', desc: 'Socket operation on non-socket'},
    89: {code: 'EDESTADDRREQ', desc: 'Destination address required'},
    90: {code: 'EMSGSIZE', desc: 'Message too long'},
    91: {code: 'EPROTOTYPE', desc: 'Protocol wrong type for socket'},
    92: {code: 'ENOPROTOOPT', desc: 'Protocol not available'},
    93: {code: 'EPROTONOSUPPORT', desc: 'Protocol not supported'},
    94: {code: 'ESOCKTNOSUPPORT', desc: 'Socket type not supported'},
    95: {code: 'EOPNOTSUPP', desc: 'Operation not supported on transport endpoint'},
    96: {code: 'EPFNOSUPPORT', desc: 'Protocol family not supported'},
    97: {code: 'EAFNOSUPPORT', desc: 'Address family not supported by protocol'},
    98: {code: 'EADDRINUSE', desc: 'Address already in use'},
    99: {code: 'EADDRNOTAVAIL', desc: 'Cannot assign requested address'},
    100: {code: 'ENETDOWN', desc: 'Network is down'},
    101: {code: 'ENETUNREACH', desc: 'Network is unreachable'},
    102: {code: 'ENETRESET', desc: 'Network dropped connection because of reset'},
    103: {code: 'ECONNABORTED', desc: 'Software caused connection abort'},
    104: {code: 'ECONNRESET', desc: 'Connection reset by peer'},
    105: {code: 'ENOBUFS', desc: 'No buffer space available'},
    106: {code: 'EISCONN', desc: 'Transport endpoint is already connected'},
    107: {code: 'ENOTCONN', desc: 'Transport endpoint is not connected'},
    108: {code: 'ESHUTDOWN', desc: 'Cannot send after transport endpoint shutdown'},
    109: {code: 'ETOOMANYREFS', desc: 'Too many references: cannot splice'},
    110: {code: 'ETIMEDOUT', desc: 'Connection timed out'},
    111: {code: 'ECONNREFUSED', desc: 'Connection refused'},
    112: {code: 'EHOSTDOWN', desc: 'Host is down'},
    113: {code: 'EHOSTUNREACH', desc: 'No route to host'},
    114: {code: 'EALREADY', desc: 'Operation already in progress'},
    115: {code: 'EINPROGRESS', desc: 'Operation now in progress'},
    116: {code: 'ESTALE', desc: 'Stale NFS file handle'},
    117: {code: 'EUCLEAN', desc: 'Structure needs cleaning'},
    118: {code: 'ENOTNAM', desc: 'Not a XENIX named type file'},
    119: {code: 'ENAVAIL', desc: 'No XENIX semaphores available'},
    120: {code: 'EISNAM', desc: 'Is a named type file'},
    121: {code: 'EREMOTEIO', desc: 'Remote I/O error'},
    122: {code: 'EDQUOT', desc: 'Quota exceeded'},
    123: {code: 'ENOMEDIUM', desc: 'No medium found'},
    124: {code: 'EMEDIUMTYPE', desc: 'Wrong medium type'},
};
